apps: 
- app:
    name: "user"
    isVisible: false
    container: "shakrron47/kcd_guatemala_nodejs:2025"
    vars:
      test1: "hola mundo User"
- app:
    name: "auth"
    isVisible: true
    container: "shakrron47/kcd_guatemala_nodejs:2025"
    vars:
      test1: "hola mundo Auth"
- app:
    name: "appa"
    isVisible: true
    container: "shakrron47/kcd_guatemala_nodejs:2025"
    vars:
      test1: "hola mundo app2"
- app:
    name: "appb"
    isVisible: true
    container: "shakrron47/kcd_guatemala_nodejs:2025"
    vars:
      test1: "hola mundo app3"
- app:
    name: "appc"
    isVisible: true
    container: "shakrron47/kcd_guatemala_nodejs:2025"
    vars:
      test1: "hola mundo app4"