{{- range $key, $val := .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ $val.name }}-s
  name: {{ $val.name }}-s
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ $val.name }}
  type: NodePort
status:
  loadBalancer: {}
---
{{ end -}}

