apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ - if  }}
  name: auth-s
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: auth-s
  type: NodePort
status:
  loadBalancer: {}

